-- [Extensions]
-- HTTP 요청을 위한 확장 (Slack Webhook용)
create extension if not exists "pg_net" with schema "extensions";

-- [Tables]
-- 1. 식당 정보 테이블
create table public.restaurants (
    id bigint generated by default as identity primary key,
    name text not null,
    location text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 메뉴 정보 테이블 (태그 포함)
create table public.menus (
    id bigint generated by default as identity primary key,
    restaurant_id bigint references public.restaurants(id) on delete cascade not null,
    name text not null,
    tags text[] default '{}', -- 예: ['한식', '매운맛']
    price integer,
    image_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 투표 테이블
create table public.votes (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) not null,
    menu_id bigint references public.menus(id) not null,
    voted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- [Indexes & Constraints]
-- 1일 1투표 제한 (DB 레벨 검증)
-- user_id와 투표 날짜(YYYY-MM-DD)를 결합하여 유니크 인덱스 생성
create unique index unique_daily_vote 
on public.votes (user_id, (voted_at::date));

-- [Row Level Security (RLS)]
-- RLS 활성화
alter table public.restaurants enable row level security;
alter table public.menus enable row level security;
alter table public.votes enable row level security;

-- 정책: 누구나 식당/메뉴 조회 가능
create policy "Public restaurants are viewable by everyone" 
on public.restaurants for select using (true);

create policy "Public menus are viewable by everyone" 
on public.menus for select using (true);

-- 정책: 인증된 사용자만 식당/메뉴 등록 (관리자 로직이 필요하다면 using 조건 수정 필요)
create policy "Authenticated users can insert menus" 
on public.menus for insert with check (auth.role() = 'authenticated');

-- 정책: 투표는 본인만 생성/삭제 가능, 조회는 누구나(실시간 집계용)
create policy "Users can vote" 
on public.votes for insert with check (auth.uid() = user_id);

create policy "Users can delete own vote" 
on public.votes for delete using (auth.uid() = user_id);

create policy "Public votes are viewable" 
on public.votes for select using (true);

-- [Functions & Triggers]

-- 1. 이메일 도메인 검증 함수 (Auth Hook)
-- auth.users 테이블에 insert 발생 시 트리거됨
create or replace function public.validate_company_email()
returns trigger as $$
begin
  -- 사내 도메인(@company.com)이 아니면 에러 발생
  if new.email not like '%@company.com' then
    raise exception '사내 이메일(@company.com)만 가입 가능합니다.';
  end if;
  return new;
end;
$$ language plpgsql security definer;

-- 트리거 연결
create trigger check_email_domain
  before insert on auth.users
  for each row execute function public.validate_company_email();

-- 2. 투표 결과 산출 및 알림 전송 함수
-- Edge Functions 또는 pg_cron에서 호출될 메인 로직
create or replace function public.calculate_result_and_notify()
returns json as $$
declare
    target_date date := current_date;
    winning_menu_id bigint;
    winning_menu_name text;
    vote_count bigint;
    slack_webhook_url text := 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'; -- 실제 URL로 교체 또는 Vault 사용
    payload jsonb;
    request_id bigint;
begin
    -- A. 최다 득표 메뉴 선정 (동점자 랜덤 픽 로직 포함)
    with vote_counts as (
        select menu_id, count(*) as cnt
        from public.votes
        where voted_at::date = target_date
        group by menu_id
    ),
    max_votes as (
        select max(cnt) as max_cnt from vote_counts
    ),
    candidates as (
        select vc.menu_id, vc.cnt
        from vote_counts vc
        join max_votes mv on vc.cnt = mv.max_cnt
    )
    select c.menu_id, c.cnt, m.name
    into winning_menu_id, vote_count, winning_menu_name
    from candidates c
    join public.menus m on c.menu_id = m.id
    order by random() -- 동점자 중 랜덤 선택
    limit 1;

    -- 투표가 없는 경우 처리
    if winning_menu_id is null then
        return json_build_object('status', 'no_votes');
    end if;

    -- B. Slack 알림 전송 (pg_net 확장 사용)
    payload := jsonb_build_object(
        'text', format('오늘의 점심 메뉴 선정 결과! 🍱%n메뉴: *%s*%n득표수: %s표', winning_menu_name, vote_count)
    );

    -- 비동기 HTTP POST 요청
    select "net".http_post(
        url := slack_webhook_url,
        body := payload,
        headers := '{"Content-Type": "application/json"}'::jsonb
    ) into request_id;

    return json_build_object(
        'status', 'success',
        'menu', winning_menu_name,
        'votes', vote_count,
        'request_id', request_id
    );
end;
$$ language plpgsql security definer;

-- [Realtime]
-- 클라이언트에서 실시간 득표 현황을 구독하기 위해 Realtime publication에 테이블 추가
-- Supabase 대시보드에서 Replication 설정이 필요할 수 있음
alter publication supabase_realtime add table public.votes;
