openapi: 3.0.0
info:
  title: User Profile Management API
  version: 1.0.0
paths:
  /api/v1/users/me:
    get:
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
    patch:
      summary: Update profile (Nickname, Bio, Image)
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                bio:
                  type: string
                profileImage:
                  type: string
                  format: binary
      responses:
        '200':
          description: Profile updated successfully
        '409':
          description: Nickname already exists